- hosts: windows
  gather_facts: no
  tasks:
    - name: Disable firewall
      win_firewall:
        state: disabled
        profiles:
          - Domain
          - Private
          - Public
      tags: disable_firewall
