- hosts: windows
  gather_facts: no
  tasks:
    - name: Enable firewall
      win_firewall:
        state: enabled
        profiles:
          - Domain
          - Private
          - Public
      tags: disable_firewall
